name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ca313c6ab7420980c11600a43d3c77fc7a4d60c957f015b1d96209e4ca4765d"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
