name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d4c9fef2ac7a2952adf1182f9900b55ff183a4d740a2e70c92b5417e20db9d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
