name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a73ae3116afeaebac5b108d143263a837043d71ce50ca5c7a1938e834bcd0eb1"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
