name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "050eb8e59fc4fb6e4535e03f4c5848b872766afb1764a6b69cf03191de6c6ec8"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
