name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6e578bd5f8d9ca246542404995beb8571dfb508b7d2723eb02aa154829d0eb4"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
