name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d831a7c2bc350d8e598d301833a88474c593bad32dc6a41ba17f2486358bde74"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
