name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b5bdbdece98c35412f18b89271427894c8e09ccbdf7c5de359031dd2ea7c29e"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
