name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87a2fda6ed7699aa6348b6f4f17b6148ab37a7a16dedd2f5fb738e250a4d991"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
