name = "Abbie's Quilt SMP"
author = "Abbie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35171abb4c45345d8a7ac54a77eb432f273b12e54b0fcf47114ccc86a1a4e96d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
